Repository impierce/identity-wallet, pull requests merged in 2024-12, with the labels that each got.

#435 fix: enable deserialization of trusted entries from both maps and arrays
  identity-wallet/src/state/trust_list/mod.rs
Labels: Bug

#433 fix: use hash-based image identifier to prevent caching, use colored background for icon fallback
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs
  unime/src/lib/components/ListItemCard.svelte
  unime/src/lib/components/image/Image.svelte
  unime/src/routes/credentials/[id]/CredentialHeader.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
Labels: Bug, Enhancement

#437 ci: adjust installed Ubuntu packages
  .github/workflows/format-lint-test.yaml
Labels: Bug

#414 fix: support `StatusList2021Entry` credentials, fetch logo from `.well-known/openid-credential-issuer`
  identity-wallet/resources/default_trust_list.json
  identity-wallet/src/state/did/validate_domain_linkage.rs
  identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  unime/src-tauri/tests/fixtures/states/accept_connection.json
Labels: Bug

#438 build: bump `oid4vc` to `7be5b72`
  Cargo.lock
  Cargo.toml
  identity-wallet/src/state/did/validate_domain_linkage.rs
Labels: Bug, Dependencies

#434 feat: update app icon, remove `Beta` from app name, add Terms & Conditions
  unime/src-tauri/app-icon.png
  unime/src-tauri/gen-static/apple/unime_iOS/Info.plist
  unime/src-tauri/icons/32x32.png
  unime/src-tauri/icons/icon.icns
  unime/src-tauri/tauri.conf.json
  unime/src/i18n/de-DE/index.ts
  unime/src/i18n/en/index.ts
  unime/src/i18n/i18n-types.ts
  unime/src/i18n/nl-NL/index.ts
  unime/src/lib/components/Checkbox.svelte
  unime/src/lib/static/svg/logo/UniMeText.svelte
  unime/src/lib/static/svg/logo/UniMeTextLight.svelte
  unime/src/routes/welcome/+page.svelte
  unime/src/routes/welcome/terms/+page.svelte
Labels: Added, Enhancement

#420 fix: content overflow & scrolling issues
  unime/src/lib/components/StatusIndicator.svelte
  unime/src/lib/components/navigation/TopNavBar.svelte
  unime/src/routes/(app)/+layout.svelte
  unime/src/routes/(app)/me/+page.svelte
  unime/src/routes/(app)/me/settings/+page.svelte
  unime/src/routes/(app)/me/settings/about/+page.svelte
  unime/src/routes/(app)/me/settings/app/+page.svelte
  unime/src/routes/(app)/me/settings/app/did/+page.svelte
  unime/src/routes/(app)/me/settings/app/keys/+page.svelte
  unime/src/routes/(app)/me/settings/app/language/+page.svelte
  unime/src/routes/(app)/me/settings/app/theme/+page.svelte
  unime/src/routes/(app)/me/settings/app/trust-list/+page.svelte
  unime/src/routes/(app)/me/settings/profile/+page.svelte
  unime/src/routes/+layout.svelte
  unime/src/routes/prompt/accept-connection/+page.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/prompt/share-credentials/+page.svelte
Labels: Bug, Enhancement, Frontend
