Repository impierce/identity-wallet, pull requests merged in 2024-04, with the labels that each got.

#109 chore: upgrade to Tauri 2.0 Beta
  .github/banner.svg
  .gitignore
  .vscode/extensions.json
  Cargo.lock
  Cargo.toml
  README.md
  identity-wallet/Cargo.toml
  unime/package-lock.json
  unime/package.json
  unime/src-tauri/.gitignore
  unime/src-tauri/Cargo.lock
  unime/src-tauri/Cargo.toml
  unime/src-tauri/capabilities/main.json
  unime/src-tauri/capabilities/mobile.json
  unime/src-tauri/icons/32x32.png
  unime/src-tauri/icons/icon.icns
  unime/src-tauri/tauri.conf.json
  unime/src-tauri/tests/common/assert_state_update.rs
Labels: Dependencies

#180 fix: prevent locale from being reset after onboarding
  identity-wallet/src/state/profile_settings/reducers/create_new.rs
  unime/src-tauri/tests/common/assert_state_update.rs
  unime/src-tauri/tests/fixtures/states/nl-NL_redirect_me.json
  unime/src-tauri/tests/fixtures/states/no_profile_nl-NL_redirect_welcome.json
  unime/src-tauri/tests/tests/get_state.rs
Labels: Bug

#181 style: configure prettier on workspace level
  .github/workflows/format-lint-test.yaml
  .gitignore
  .prettierignore
  .prettierrc.js
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  identity-wallet/.gitignore
  identity-wallet/resources/ngdil.json
  identity-wallet/resources/onboarding-2.json
  identity-wallet/resources/onboarding.json
  package-lock.json
  package.json
  unime/.gitignore
  unime/.prettierignore
  unime/.prettierrc.js
  unime/package-lock.json
  unime/package.json
  unime/src-tauri/resources/onboarding.json
Labels: Chore

#186 fix: use hashed `logo_uri` as identifier for temporary image assets
  identity-wallet/src/persistence.rs
  identity-wallet/src/state/connections/reducers/handle_siopv2_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs
  unime/package-lock.json
  unime/package.json
  unime/src-tauri/tests/tests/assets_download.rs
  unime/src/lib/utils.test.ts
  unime/src/lib/utils.ts
  unime/src/routes/prompt/accept-connection/+page.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/prompt/share-credentials/+page.svelte
Labels: Bug

#187 refactor: update action payload
  identity-wallet/bindings/actions/UpdateSortingPreference.ts
  unime/src/lib/connections/sorting/SortingSheet.svelte
  unime/src/lib/connections/sorting/SortingSheetButton.svelte
  unime/src/lib/credentials/CredentialList.svelte
Labels: Into feature branch

#203 chore: Upgrade SvelteKit to v2
  unime/package-lock.json
  unime/package.json
  unime/src/app.d.ts
  unime/src/lib/app/LanguageSelect.svelte
  unime/src/lib/app/WelcomeMessage.svelte
  unime/src/lib/app/settings/EmojiAvatarSelect.svelte
  unime/src/lib/app/settings/ThemeSelect.svelte
  unime/src/lib/components/molecules/IconMessage.svelte
  unime/src/lib/components/molecules/Search.svelte
  unime/src/lib/components/molecules/navigation/BottomNavBar.svelte
  unime/src/lib/connections/ConnectionData.svelte
  unime/src/lib/connections/ConnectionSummary.svelte
  unime/src/lib/connections/ConnectionsList.svelte
  unime/src/lib/credentials/CredentialList.svelte
  unime/src/lib/credentials/Favorites.svelte
  unime/src/lib/events/History.svelte
  unime/src/lib/events/HistoryEntry.svelte
  unime/src/lib/journeys/UserJourney.svelte
  unime/src/lib/journeys/goals/GoalItem.svelte
  unime/src/lib/stores.ts
  unime/src/routes/(app)/+layout.svelte
  unime/src/routes/(app)/activity/+page.svelte
  unime/src/routes/(app)/activity/connection/[id]/+page@.svelte
  unime/src/routes/(app)/me/+page.svelte
  unime/src/routes/(app)/me/search/+page.svelte
  unime/src/routes/(app)/me/search/RecentSearches.svelte
  unime/src/routes/(app)/me/settings/+page.svelte
  unime/src/routes/(app)/me/settings/about/+page.svelte
  unime/src/routes/(app)/me/settings/app/+page.svelte
  unime/src/routes/(app)/me/settings/app/language/+page.svelte
  unime/src/routes/(app)/me/settings/app/theme/+page.svelte
  unime/src/routes/(app)/me/settings/backup/+page.svelte
  unime/src/routes/(app)/me/settings/profile/+page.svelte
  unime/src/routes/(app)/me/settings/profile/name/+page.svelte
  unime/src/routes/(app)/scan/+page@.svelte
  unime/src/routes/(journey)/goals/+page.svelte
  unime/src/routes/(journey)/goals/[id]/+layout.svelte
  unime/src/routes/(journey)/goals/[id]/faqs/+page.svelte
  unime/src/routes/(journey)/goals/[id]/step/[id]/+page.svelte
  unime/src/routes/+error.svelte
  unime/src/routes/+layout.svelte
  unime/src/routes/+page.svelte
  unime/src/routes/badges/[id]/+page.svelte
  unime/src/routes/credentials/[id]/+page.svelte
  unime/src/routes/prompt/accept-connection/+page.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/prompt/password-required/+page.svelte
  unime/src/routes/prompt/share-credentials/+page.svelte
  unime/src/routes/welcome/+page.svelte
  unime/src/routes/welcome/customize/name/+page.svelte
  unime/src/routes/welcome/password/+page.svelte
  unime/src/routes/welcome/password/completed/+page.svelte
  unime/src/routes/welcome/password/confirm/+page.svelte
  unime/src/routes/welcome/password/utils.ts
  unime/src/routes/welcome/pledge/+page.svelte
  unime/src/routes/welcome/terms/+page.svelte
  unime/svelte.config.js
  unime/tsconfig.json
  unime/vite.config.ts
Labels: Dependencies

#202 fix: link connection to badge, replace encoding with hashing for connection ids
  .vscode/settings.json
  identity-wallet/bindings/display-credential/DisplayCredential.ts
  identity-wallet/src/state/connections/mod.rs
  identity-wallet/src/state/credentials/mod.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  identity-wallet/src/state/search/reducers/search_query.rs
  unime/src-tauri/tests/common/assert_state_update.rs
  unime/src-tauri/tests/fixtures/states/credential_redirect_me.json
  unime/src-tauri/tests/fixtures/states/did_redirect_me.json
  unime/src-tauri/tests/fixtures/states/four_credentials_redirect_me.json
  unime/src/lib/connections/ConnectionsList.svelte
  unime/src/lib/events/History.svelte
  unime/src/routes/(app)/activity/+page.svelte
  unime/src/routes/(app)/activity/connection/[id]/+page@.svelte
  unime/src/routes/badges/[id]/+page.svelte
  unime/src/routes/prompt/accept-connection/+page.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/prompt/share-credentials/+page.svelte
Labels: Bug

#191 feat(backend): add sorting based on locale
  Cargo.lock
  identity-wallet/Cargo.toml
  identity-wallet/bindings/actions/UpdateSortingPreference.ts
  identity-wallet/src/state/common/actions/get_state.rs
  identity-wallet/src/state/common/actions/unlock_storage.rs
  identity-wallet/src/state/connections/actions/connection_accepted.rs
  identity-wallet/src/state/credentials/actions/credential_offers_selected.rs
  identity-wallet/src/state/credentials/actions/update_credential_metadata.rs
  identity-wallet/src/state/credentials/mod.rs
  identity-wallet/src/state/dev_mode/actions/dev_profile.rs
  identity-wallet/src/state/profile_settings/actions/set_locale.rs
  identity-wallet/src/state/profile_settings/actions/update_sorting_preference.rs
  identity-wallet/src/state/profile_settings/mod.rs
  identity-wallet/src/state/profile_settings/reducers/update_sorting_preference.rs
  unime/src-tauri/tests/common/assert_state_update.rs
  unime/src-tauri/tests/fixtures/actions/connection_sort_name_az.json
  unime/src-tauri/tests/fixtures/actions/credential_sort_issue.json
  unime/src-tauri/tests/fixtures/actions/credential_sort_issue_reverse.json
  unime/src-tauri/tests/fixtures/states/credential_redirect_me.json
  unime/src-tauri/tests/fixtures/states/credential_share_credential.json
  unime/src-tauri/tests/fixtures/states/five_connections_sort_unicode_random_alphabets_name_az.json
  unime/src-tauri/tests/fixtures/states/five_connections_unicode_random_alphabets.json
  unime/src-tauri/tests/fixtures/states/four_credentials_sort_identical_issue_dates.json
  unime/src-tauri/tests/fixtures/states/four_credentials_sort_identical_issue_dates_reverse.json
  unime/src-tauri/tests/fixtures/states/shenron_six_credentials_two_connections.json
  unime/src-tauri/tests/fixtures/states/shenron_six_credentials_two_connections_search.json
  unime/src-tauri/tests/fixtures/states/three_connections.json
  unime/src-tauri/tests/tests/load_dev_profile.rs
  unime/src-tauri/tests/tests/sorting.rs
Labels: Added, Into feature branch
