Repository impierce/identity-wallet, pull requests merged in 2024-08, with the labels that each got.

#236 feat: add support for `ES256` signature algorithm
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  identity-wallet/bindings/actions/Action.ts
  identity-wallet/bindings/actions/SetPreferredKeyType.ts
  identity-wallet/bindings/profile_settings/ProfileSettings.ts
  identity-wallet/bindings/user_prompt/CurrentUserPrompt.ts
  identity-wallet/src/command.rs
  identity-wallet/src/state/actions.rs
  identity-wallet/src/state/common/reducers/unlock_storage.rs
  identity-wallet/src/state/connections/reducers/handle_siopv2_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  identity-wallet/src/state/did/actions/mod.rs
  identity-wallet/src/state/did/actions/set_preferred_keytype.rs
  identity-wallet/src/state/did/reducers/mod.rs
  identity-wallet/src/state/did/reducers/preferred_keytype.rs
  identity-wallet/src/state/did/reducers/preferred_method.rs
  identity-wallet/src/state/mod.rs
  identity-wallet/src/state/profile_settings/mod.rs
  identity-wallet/src/state/profile_settings/reducers/create_new.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  identity-wallet/src/stronghold.rs
  identity-wallet/src/subject.rs
  package-lock.json
  unime/eslint.config.js
  unime/package.json
  unime/src-tauri/Cargo.toml
  unime/src-tauri/tests/common/assert_state_update.rs
  unime/src-tauri/tests/common/mod.rs
  unime/src-tauri/tests/fixtures/actions/qr_scanned_id_token.json
  unime/src-tauri/tests/fixtures/actions/qr_scanned_vp_token.json
  unime/src-tauri/tests/fixtures/states/credential_redirect_me.json
  unime/src/routes/(app)/me/settings/app/+page.svelte
  unime/src/routes/(app)/me/settings/app/did/+page.svelte
  unime/src/routes/(app)/me/settings/app/keys/+page.svelte
Labels: Added

#303 fix: replace `jsonwebtoken::decode` with base64 decoding
  identity-wallet/src/state/core_utils/helpers.rs
  identity-wallet/src/state/credentials/mod.rs
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  unime/src-tauri/tests/tests/qr_code_scanned.rs
Labels: Bug

#304 refactor: make `AppState` immutable in all reducer signatures
  identity-wallet/src/state/connections/reducers/handle_siopv2_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/dev_mode/reducers/toggle_dev_mode.rs
  identity-wallet/src/state/profile_settings/reducers/create_new.rs
Labels: Backend, Refactor

#325 fix: update logic to determine credential display name
  identity-wallet/src/state/credentials/mod.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  unime/src-tauri/tests/tests/get_state.rs
  unime/src-tauri/tests/tests/load_dev_profile.rs
  unime/src-tauri/tests/tests/qr_code_scanned.rs
Labels: Bug

#323 chore: minor DX/UX improvements
  README.md
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  package-lock.json
  unime/package.json
  unime/src-tauri/gen-static/apply.sh
  unime/src-tauri/tests/fixtures/states/four_credentials_redirect_me.json
  unime/src/lib/components/ListItemCard.svelte
  unime/src/lib/components/navigation/TopNavBar.svelte
  unime/src/lib/icons/index.ts
  unime/src/lib/stores.ts
  unime/src/routes/(app)/scan/+page@.svelte
  unime/src/routes/+layout.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/welcome/completed/+page.svelte
  unime/src/routes/welcome/password/confirm/+page.svelte
  unime/src/routes/welcome/utils.ts
Labels: Enhancement

#332 ci: release version 0.6.7
  .npmrc
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  package-lock.json
  unime/eslint.config.js
  unime/package.json
  unime/src-tauri/.gitignore
  unime/src-tauri/Cargo.toml
  unime/src-tauri/gen-static/android/app/build.gradle.kts
  unime/src-tauri/gen-static/android/app/tauri.properties
  unime/src-tauri/gen-static/apple/ExportOptions.plist
  unime/src-tauri/gen-static/apple/unime_iOS/Info.plist
  unime/src-tauri/gen-static/apply.sh
  unime/src-tauri/tauri.conf.json
  unime/src/lib/components/credentials/CredentialList.svelte
  unime/src/routes/(app)/me/+page.svelte
  unime/src/routes/(app)/me/settings/about/+page.svelte
Labels: Dependencies

#338 feat: add support for ES256 Domain Linkage Verification
  Cargo.lock
  identity-wallet/Cargo.toml
  identity-wallet/src/state/did/validate_domain_linkage.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
Labels: Enhancement

#335 chore(deps): pin all Tauri versions
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  unime/src-tauri/Cargo.toml
Labels: Dependencies

#340 feat: add tab separator
  unime/src/lib/components/navigation/Tabs.svelte
Labels: Enhancement
