Repository impierce/identity-wallet, pull requests merged in 2024-10, with the labels that each got.

#370 ci: release version 0.6.12
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  unime/package.json
  unime/src-tauri/Cargo.toml
  unime/src-tauri/gen-static/android/app/tauri.properties
  unime/src-tauri/gen-static/apple/unime_iOS/Info.plist
  unime/src-tauri/tauri.conf.json
  unime/src/routes/(app)/me/settings/about/+page.svelte
Labels: Dependencies

#394 fix: set SD-JWT format check back to `VcSdJwt`
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
Labels: Bug, Into feature branch, Priority

#386 feat: display `alignment` & `criteria` for Open Badges 3.0
  .github/workflows/format-lint-test.yaml
  identity-wallet/src/state/did/validate_domain_linkage.rs
  package.json
  pnpm-lock.yaml
  unime/package.json
  unime/src/i18n/de-DE/index.ts
  unime/src/i18n/en/index.ts
  unime/src/i18n/i18n-types.ts
  unime/src/i18n/nl-NL/index.ts
  unime/src/routes/credentials/[id]/OpenBadgeRenderer.svelte
Labels: Into feature branch

#396 fix: use hash-based image identifier to prevent caching, use colored background for icon fallback
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs
  unime/src/lib/components/ListItemCard.svelte
  unime/src/lib/components/image/Image.svelte
  unime/src/routes/credentials/[id]/CredentialHeader.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
Labels: Into feature branch

#397 fix: trusted issuer domain url validation
  identity-wallet/resources/default_trust_list.json
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
Labels: Into feature branch
