Repository impierce/identity-wallet, pull requests merged in 2024-06, with the labels that each got.

#241 fix: reverse sorting order labels, update bindings imports
  unime/src/lib/app/locales.ts
  unime/src/lib/connections/ConnectionSummary.svelte
  unime/src/lib/connections/ConnectionsList.svelte
  unime/src/lib/connections/sorting/SortingSheetButton.svelte
  unime/src/lib/connections/utils.test.ts
  unime/src/lib/connections/utils.ts
  unime/src/lib/credentials/CredentialList.svelte
  unime/src/lib/credentials/Favorites.svelte
  unime/src/lib/events/History.svelte
  unime/src/lib/events/HistoryEntry.svelte
  unime/src/routes/(app)/activity/connection/[id]/+page@.svelte
  unime/src/routes/(app)/me/search/RecentSearches.svelte
  unime/src/routes/utils.ts
Labels: Bug

#231 feat: show loading state for user prompts
  unime/src/lib/components/atoms/Button.svelte
  unime/src/lib/components/atoms/LoadingSpinner.svelte
  unime/src/lib/components/molecules/navigation/TopNavBar.svelte
  unime/src/routes/(app)/scan/+page@.svelte
  unime/src/routes/prompt/accept-connection/+page.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/prompt/share-credentials/+page.svelte
Labels: Enhancement

#237 feat: emit errors in core, display error toasts in frontend
  identity-wallet/bindings/CurrentUserPrompt.ts
  identity-wallet/src/command.rs
  identity-wallet/src/state/user_prompt.rs
  unime/src/i18n/de-DE/index.ts
  unime/src/i18n/en/index.ts
  unime/src/i18n/i18n-types.ts
  unime/src/i18n/nl-NL/index.ts
  unime/src/lib/components/molecules/toast/ErrorToast.svelte
  unime/src/lib/stores.ts
  unime/src/routes/(app)/scan/+page@.svelte
  unime/src/routes/+layout.svelte
  unime/src/routes/prompt/accept-connection/+page.svelte
  unime/src/routes/prompt/credential-offer/+page.svelte
  unime/src/routes/prompt/share-credentials/+page.svelte
Labels: Enhancement

#245 feat: validate domain linkage
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  identity-wallet/bindings/AppState.ts
  identity-wallet/bindings/CurrentUserPrompt.ts
  identity-wallet/bindings/user_prompt/CurrentUserPrompt.ts
  identity-wallet/bindings/user_prompt/ValidationResult.ts
  identity-wallet/bindings/user_prompt/ValidationStatus.ts
  identity-wallet/src/state/common/reducers/reset_state.rs
  identity-wallet/src/state/did/mod.rs
  identity-wallet/src/state/did/validate_domain_linkage.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  identity-wallet/src/state/user_prompt.rs
  identity-wallet/src/subject.rs
  unime/package-lock.json
  unime/package.json
  unime/src-tauri/tests/fixtures/states/accept_connection.json
  unime/src/i18n/de-DE/index.ts
  unime/src/i18n/en/index.ts
  unime/src/i18n/i18n-types.ts
  unime/src/i18n/nl-NL/index.ts
  unime/src/lib/components/molecules/ListItemCard.svelte
  unime/src/lib/connections/ConnectionsList.svelte
  unime/src/routes/(app)/scan/+page@.svelte
  unime/src/routes/credentials/[id]/+page.svelte
  unime/src/routes/prompt/accept-connection/+page.svelte
Labels: Added

#252 feat: add link to Selv demo
  unime/src/i18n/de-DE/index.ts
  unime/src/i18n/en/index.ts
  unime/src/i18n/i18n-types.ts
  unime/src/i18n/nl-NL/index.ts
  unime/src/lib/app/settings/EmojiAvatarSelect.svelte
  unime/src/lib/credentials/CredentialList.svelte
  unime/src/lib/static/svg/logo/demos/Ngdil.svelte
  unime/src/lib/static/svg/logo/demos/Selv.svelte
  unime/src/routes/(app)/me/+page.svelte
Labels: Added

#248 fix: implement issuer display properties according to spec
  identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs
Labels: Bug
