Repository impierce/identity-wallet, pull requests merged in 2025-09, with the labels that each got.

#594 feat: support PIN code during issuance flow
  Cargo.lock
  Cargo.toml
  identity-wallet/bindings/actions/CodeReceived.ts
  identity-wallet/bindings/actions/CredentialOffersSelected.ts
  identity-wallet/bindings/user_prompt/CurrentUserPrompt.ts
  identity-wallet/src/state/credentials/actions/authorization_code_received.rs
  identity-wallet/src/state/credentials/actions/credential_offers_selected.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/credentials/reducers/send_token_request.rs
  identity-wallet/src/state/dev_mode/reducers/dragon_dynamic_profile.rs
  identity-wallet/src/state/qr_code/reducers/read_credential_offer.rs
  identity-wallet/src/state/user_prompt.rs
  unime/src/routes/prompt/credential-offer/+page.svelte
Labels: Added, Frontend, Backend

#620 fix: move `target`-specific dependencies
  unime/src-tauri/Cargo.toml
Labels: Bug

#619 refactor: various minor adjustments
  unime/src-tauri/gen-static/android/app/build.gradle.kts
  unime/src-tauri/gen-static/apple/ExportOptions.plist
  unime/src/routes/(app)/me/settings/about/+page.ts
Labels: Enhancement

#625 build: bump `identity.rs` dependencies to `v1.6.0-beta.7`
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  unime/src-tauri/Cargo.toml
Labels: Dependencies, Backend
