Repository impierce/identity-wallet, pull requests merged in 2025-08, with the labels that each got.

#553 feat: hide `Developer mode` setting by default
  identity-wallet/.gitignore
  identity-wallet/bindings/AppState.ts
  identity-wallet/bindings/actions/Action.ts
  identity-wallet/bindings/dev_mode/ShowDevModeSetting.ts
  identity-wallet/src/state/actions.rs
  identity-wallet/src/state/dev_mode/actions/mod.rs
  identity-wallet/src/state/dev_mode/actions/show_setting.rs
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  identity-wallet/src/state/dev_mode/reducers/mod.rs
  identity-wallet/src/state/dev_mode/reducers/show_setting.rs
  identity-wallet/src/state/mod.rs
  unime/src/lib/components/Toast.svelte
  unime/src/lib/components/index.ts
  unime/src/lib/stores.ts
  unime/src/routes/(app)/me/settings/about/+page.svelte
  unime/src/routes/(app)/me/settings/app/+page.svelte
  unime/src/routes/+layout.svelte
  unime/src/routes/ErrorToast.svelte
Labels: Enhancement

#586 chore(deps-dev): bump all `@sveltejs` deps, bump `vite`
  pnpm-lock.yaml
  unime/package.json
  unime/src/routes/(app)/me/settings/app/trust-list/[id]/+page.svelte
  unime/src/routes/(journey)/goals/[id]/+layout.svelte
  unime/src/routes/(journey)/goals/[id]/faqs/+page.svelte
Labels: Dependencies

#589 feat: add Finnish (`fi-FI`) and Swedish (`sv-FI`) translations
  unime/src/i18n/fi-FI/index.ts
  unime/src/i18n/i18n-types.ts
  unime/src/i18n/i18n-util.async.ts
  unime/src/i18n/i18n-util.sync.ts
  unime/src/i18n/i18n-util.ts
  unime/src/i18n/sv-FI/index.ts
Labels: Added

#576 fix: configure `rustls_platform_verifier` for Android builds
  Cargo.lock
  Cargo.toml
  README.md
  identity-wallet/Cargo.toml
  identity-wallet/src/command.rs
  identity-wallet/src/state/common/reducers/unlock_storage.rs
  identity-wallet/src/state/core_utils/mod.rs
  identity-wallet/src/state/dev_mode/reducers/ferris_static_profile.rs
  identity-wallet/src/state/did/validate_domain_linkage.rs
  identity-wallet/src/state/did/validate_linked_verifiable_presentations.rs
  identity-wallet/src/state/profile_settings/reducers/create_new.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  identity-wallet/src/subject.rs
  unime/src-tauri/Cargo.toml
  unime/src-tauri/gen-static/android/app/build.gradle.kts
  unime/src-tauri/gen-static/android/app/proguard-rules.pro
  unime/src-tauri/gen-static/android/app/src/main/java/com/impierce/identity_wallet/MainActivity.kt
  unime/src-tauri/gen-static/android/gradle/libs.versions.toml
  unime/src-tauri/gen-static/apply.sh
  unime/src-tauri/src/lib.rs
  unime/src-tauri/tests/common/mod.rs
Labels: Bug, Backend

#593 feat: support deep linking for `openid://` and `openid-credential-offer://`
  Cargo.lock
  Cargo.toml
  identity-wallet/bindings/AppState.ts
  identity-wallet/src/state/common/reducers/get_state.rs
  identity-wallet/src/state/common/reducers/unlock_storage.rs
  identity-wallet/src/state/core_utils/helpers.rs
  identity-wallet/src/state/credentials/reducers/send_credential_request.rs
  identity-wallet/src/state/mod.rs
  pnpm-lock.yaml
  unime/UniMe.desktop
  unime/package.json
  unime/src-tauri/Cargo.toml
  unime/src-tauri/capabilities/main.json
  unime/src-tauri/gen-static/apple/ExportOptions.plist
  unime/src-tauri/gen-static/apple/unime_iOS/Info.plist
  unime/src-tauri/src/lib.rs
  unime/src-tauri/tauri.conf.json
  unime/src/lib/stores.ts
  unime/src/routes/+layout.svelte
Labels: Added, Frontend, Backend

#578 feat: migrate to OID4VP draft 28, implement DCQL
  Cargo.lock
  Cargo.toml
  identity-wallet/src/state/connections/reducers/handle_siopv2_authorization_request.rs
  identity-wallet/src/state/credentials/mod.rs
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  unime/src-tauri/tests/fixtures/actions/qr_scanned_vp_token.json
  unime/src-tauri/tests/fixtures/states/self_issued_profile.json
Labels: Added, Breaking change, Dependencies, Backend

#598 feat: show PIN input in user prompt
  identity-wallet/bindings/actions/CodeReceived.ts
  identity-wallet/bindings/actions/CredentialOffersSelected.ts
  identity-wallet/bindings/user_prompt/CurrentUserPrompt.ts
  identity-wallet/src/state/user_prompt.rs
  unime/src/routes/prompt/credential-offer/+page.svelte
Labels: Into feature branch

#600 build: bump `oid4vc`, return error when no credential matches query
  Cargo.lock
  Cargo.toml
  identity-wallet/src/error.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
Labels: Dependencies, Backend
