Repository impierce/identity-wallet, pull requests merged in 2025-04, with the labels that each got.

#536 feat: enable locale `en-GB`, refine base `en` translations
  unime/src/i18n/en-GB/index.ts
  unime/src/i18n/en/index.ts
  unime/src/lib/locales.ts
Labels: Added

#535 refactor: debug app state
  .gitignore
  docs/debugging.md
  identity-wallet/src/command.rs
  identity-wallet/src/state/did/validate_domain_linkage.rs
  unime/.env.example
Labels: Enhancement

#534 ci: scope `CODEOWNERS`
  .github/CODEOWNERS
Labels: Enhancement

#537 feat: move OBv3 `Achievement type` above `Alignment`
  unime/src/routes/credentials/[id]/OpenBadgeRenderer.svelte
Labels: Enhancement

#387 feat: receive, display and share SD-JWT credentials
  Cargo.lock
  Cargo.toml
  identity-wallet/Cargo.toml
  identity-wallet/bindings/credentials/DisplayCredential.ts
  identity-wallet/src/error.rs
  identity-wallet/src/state/credentials/mod.rs
  identity-wallet/src/state/credentials/reducers/handle_oid4vp_authorization_request.rs
  identity-wallet/src/state/qr_code/reducers/read_authorization_request.rs
  identity-wallet/src/state/search/reducers/search_query.rs
Labels: Added

#498 feat: introduce versioning of `AppState`, prepare data migration path
  identity-wallet/bindings/AppState.ts
  identity-wallet/src/data_migration.rs
  identity-wallet/src/error.rs
  identity-wallet/src/lib.rs
  identity-wallet/src/persistence.rs
  identity-wallet/src/state/mod.rs
  unime/src/lib/stores.ts
Labels: Added, V1 MVP
